baseURL = "https://beltron.netlify.app/"
languageCode = "en-us"
theme = "beltron"
enableEmoji = true
DefaultContentLanguage = "hi"
googleAnalytics = ""
enableRobotsTXT = true


[languages]

  [languages.en]
  title = "DEO Union Bihar"
  weight = 2
  contentDir = "content/en"
  languageName = "English"
  [[languages.en.menu.main]]
  url    = "/"
  name   = "Home"
  weight = 1

  [languages.hi]
  title = "डाटा इंट्री ऑपरेटर संघ बिहार"
  weight = 1
  contentDir = "content/hi"
  languageName = "हिन्दी"
  [[languages.hi.menu.main]]
  url    = "/"
  name   = "मुख्य"
  weight = 1

[Taxonomies]
  tag = "tags"

[params]
  favicon = ""
  site_logo = "/images/logo.jpeg"
  author = "Sarvottam Kumar"
  GitHubUser = "sarru1291"
  authorlocation = "Noida, India"
  authorwebsite = "https://www.sarvottamkumar.in"
  authorbio= "Developer, Linux and open source writer"
  facebook = "https://www.facebook.com/BeltronDEO2019/"
  twitter = "https://twitter.com/beltrondeo2020"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  telegram = "https://t.me/joinchat/QF2Krllj-K6sxc5T7p8HQg"
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  recent_posts_number = 2
  commentoEnable = true
  disqusShortname = "ss"
  showVisitedLinks = false
  disableSearch = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableNextPrev = false
  [params.navigation]
      help = "Help"

[permalinks]
  posts = "/:06/:1/:2/:title/"


  
