baseURL = "https://beltron.netlify.app/"
languageCode = "en-us"
title = "बिहार राज्य अनियोजित बेल्ट्रान डाटा इंट्री ऑपरेटर संघ"
theme = "beltron"
#copyright = "All rights reserved"
enableEmoji = true
footnoteReturnLinkContents = "↩"

DefaultContentLanguage = "hi"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[Languages]
[Languages.hi]
title = "बिहार राज्य अनियोजित बेल्ट्रान डाटा इंट्री ऑपरेटर संघ"
weight = 1
languageName = "Hindi"

[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 2
languageName = "English"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
  
