baseURL = "https://beltron.netlify.app/"
languageCode = "en-us"
title = "बिहार राज्य अनियोजित बेल्ट्रान डाटा इंट्री ऑपरेटर संघ"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true


[params]
  favicon = ""
  site_logo = "images/logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/BeltronDEO2019/"
  twitter = "https://twitter.com/beltrondeo2020"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  telegram = "https://t.me/joinchat/QF2Krllj-K6sxc5T7p8HQg"
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  commentoEnable = true
  disqusShortname = "ss"
