baseURL = "https://beltron.netlify.app/"
languageCode = "en-us"
theme = "beltron"
enableEmoji = true
DefaultContentLanguage = "hi"
googleAnalytics = ""
enableRobotsTXT = true

[languages]

  [languages.en]
  title = "Bihar State Unplanned Beltron Data Entry Operator Association"
  weight = 2
  contentDir = "content/en"
  languageName = "English"

  [languages.hi]
  title = "बिहार राज्य अनियोजित बेल्ट्रान डाटा इंट्री ऑपरेटर संघ"
  weight = 1
  contentDir = "content/hi"
  languageName = "Hindi"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Taxonomies]
  tag = "tags"

[params]
  favicon = ""
  site_logo = "images/logo.png"
  description = "Bihar Beltron DEO 2020 बिहार राज्य अनियोजित बेल्ट्रान डाटा इंट्री ऑपरेटर संघ"
  author = "Sarvottam Kumar"
  GitHubUser = "sarru1291"
  authorlocation = "Noida, India"
  authorwebsite = "https://www.sarvottamkumar.in"
  authorbio= "Developer, Linux and open source writer"
  facebook = "https://www.facebook.com/BeltronDEO2019/"
  twitter = "https://twitter.com/beltrondeo2020"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  telegram = "https://t.me/joinchat/QF2Krllj-K6sxc5T7p8HQg"
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  commentoEnable = true
  disqusShortname = "ss"
  showVisitedLinks = false
  disableSearch = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableNextPrev = false
  [params.navigation]
      help = "Help"

  
