baseURL = "https://beltron.netlify.app/"
languageCode = "en-us"
theme = "beltron"
enableEmoji = true
DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true

[languages]

  [languages.en]
  title = "DEO Union Bihar"
  weight = 2
  contentDir = "content/en"
  languageName = "English"

  [languages.hi]
  title = "डाटा इंट्री ऑपरेटर संघ बिहार"
  weight = 1
  contentDir = "content/hi"
  languageName = "Hindi"

[Taxonomies]
  tag = "tags"

[params]
  favicon = ""
  site_logo = "images/logo.jpeg"
  description = "Data Entry Operator Union Bihar"
  author = "Sarvottam Kumar"
  GitHubUser = "sarru1291"
  authorlocation = "Noida, India"
  authorwebsite = "https://www.sarvottamkumar.in"
  authorbio= "Developer, Linux and open source writer"
  facebook = "https://www.facebook.com/BeltronDEO2019/"
  twitter = "https://twitter.com/beltrondeo2020"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  telegram = "https://t.me/joinchat/QF2Krllj-K6sxc5T7p8HQg"
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  recent_posts_number = 2
  commentoEnable = true
  disqusShortname = "ss"
  showVisitedLinks = false
  disableSearch = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableNextPrev = false
  [params.navigation]
      help = "Help"

[permalinks]
  posts = "/:06/:1/:2/:title/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url="/"
    weight = 1
  
